/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package covidsos1;

import static covidsos1.surveyform.cname;
import static covidsos1.surveyform.cphno;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author Anirudh Pandita
 */
public class report extends javax.swing.JFrame {

    /**
     * Creates new form report
     */
    public report() {
        initComponents();
    }
public void setup(String uid,String pid){
    Connection myConn = null;
		PreparedStatement myStmt = null;
                PreparedStatement myStmt1 = null;
		ResultSet myRs = null;
                ResultSet myRs1 = null;
                try {
			// 1. Get a connection to database
			myConn = DriverManager.getConnection("jdbc:mysql://localhost:3306/pincode", "root" , "Kuld1972poon");
			
			// 2. Prepare statement
                          String query = "SELECT * FROM `pincode`.`clients`"+"WHERE `USERNAME`=?"+"AND `PASSWORD`=?";
			myStmt = myConn.prepareStatement(query);
			   myStmt = myConn.prepareStatement(query);
                     myStmt.setString(1,uid);
                     myStmt.setString(2,pid);
                   myRs = myStmt.executeQuery();
                   myRs.next();
			name.setText("NAME:"+myRs.getString("NAME"));
                        String a=myRs.getString("NAME");
                        phno.setText("PHONE NO:"+myRs.getString("PHONE NO"));
                        String b=myRs.getString("PHONE NO");
                        card.setText("AADHAR CARD:"+myRs.getString("AADHAR CARD"));
                        String query1 = "SELECT * FROM `pincode`.`callreport`"+"WHERE `NAME`=?"+"AND `PHONE NO`=?";
		         myStmt1=myConn.prepareStatement(query1);
                         myStmt1.setString(1,a);
                         myStmt1.setString(2,b);
                         myRs1=myStmt1.executeQuery();
                         myRs1.next();
                         hos.setText("HOSPITAL:"+myRs1.getString("HOSPITAL"));
                         pla.setText("PLASMA:"+myRs1.getString("PLASMA"));
                         food.setText("FOOD:"+myRs1.getString("FOOD"));
                         med.setText("MEDICINE:"+myRs1.getString("PHARMACY"));
             
			// 4. Execute SQL query
			
    }catch (SQLException exc) {
			exc.printStackTrace();
		}
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        phno = new javax.swing.JLabel();
        hos = new javax.swing.JLabel();
        pla = new javax.swing.JLabel();
        med = new javax.swing.JLabel();
        food = new javax.swing.JLabel();
        card = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("COVID SOS");

        name.setText("NAME:");

        phno.setText("PHONE NO:");

        hos.setText("HOSPITAL REGISTRED:");

        pla.setText("PLASMA:");

        med.setText("MEDICINE:");

        food.setText("FOOD:");

        card.setText("AADHAR CARD:");

        jLabel9.setText("ADDRESS");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("CALL COMPLETION REPORT");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(food)
                            .addComponent(jLabel9)
                            .addComponent(med)
                            .addComponent(pla)
                            .addComponent(hos)
                            .addComponent(card)
                            .addComponent(phno)
                            .addComponent(name)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(219, 219, 219)
                        .addComponent(jLabel10))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(261, 261, 261)
                        .addComponent(jLabel1)))
                .addContainerGap(256, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addGap(42, 42, 42)
                .addComponent(name)
                .addGap(18, 18, 18)
                .addComponent(phno)
                .addGap(26, 26, 26)
                .addComponent(card)
                .addGap(37, 37, 37)
                .addComponent(hos)
                .addGap(46, 46, 46)
                .addComponent(pla)
                .addGap(49, 49, 49)
                .addComponent(med)
                .addGap(43, 43, 43)
                .addComponent(food)
                .addGap(48, 48, 48)
                .addComponent(jLabel9)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new report().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel card;
    private javax.swing.JLabel food;
    private javax.swing.JLabel hos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel med;
    private javax.swing.JLabel name;
    private javax.swing.JLabel phno;
    private javax.swing.JLabel pla;
    // End of variables declaration//GEN-END:variables
}
