/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package covidsos1;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Anirudh Pandita
 */
public class surveyform extends javax.swing.JFrame {
public static String rid=null;
public static String cname,cphno;
public static int j;
public static String k,l;
public static int lo;
    /**
     * Creates new form surveyform
     */
    public surveyform() {
        initComponents();
        
    }
    
    public ArrayList<getid> rev_list(){
        ArrayList<getid> rev_list = new ArrayList<>();
         Connection myConn = null;
		PreparedStatement myStmt = null;
		ResultSet myRs = null;
		
		try {
			// 1. Get a connection to database
			myConn = DriverManager.getConnection("jdbc:mysql://localhost:3306/pincode", "root" , "Kuld1972poon");
			
			// 2. Prepare statement
                        String query = "SELECT `REV ID` FROM `pincode`.`rev1`";
			myStmt = myConn.prepareStatement(query);
			
			// 3. Set the parameters
			
			// 4. Execute SQL query
			myRs = myStmt.executeQuery();
                       getid r1;
                        while(myRs.next()){
                           r1= new getid(myRs.getString("REV ID"));
                           rev_list.add(r1);
                        }
                        
                        
    }catch (SQLException exc) {
			exc.printStackTrace();
		}
        return rev_list;
    }
   
    public void finallist(int i){
        
        ArrayList<getid> list = rev_list();
        if(i>=list.size()){
            j=0;
            i=0;
            rid=list.get(0).getId();
            return;
        }
        rid=list.get(i).getId();
       
    }
    
    public void initial(String uid,String pid){
       System.out.print(uid+" "+pid);
       k=uid;
       l=pid;
       Connection myConn = null;
		PreparedStatement myStmt = null;
		ResultSet myRs = null;
                try {
			// 1. Get a connection to database
			myConn = DriverManager.getConnection("jdbc:mysql://localhost:3306/pincode", "root" , "Kuld1972poon");
			
			// 2. Prepare statement
                          String query = "SELECT * FROM `pincode`.`clients`"+"WHERE `USERNAME`=?"+"AND `PASSWORD`=?";
			myStmt = myConn.prepareStatement(query);
			   myStmt = myConn.prepareStatement(query);
                     myStmt.setString(1,uid);
                     myStmt.setString(2,pid);
                   myRs = myStmt.executeQuery();
                   myRs.next();
			inname.setText("Name:"+myRs.getString("NAME"));
                        inphno.setText("Phone no:"+myRs.getString("PHONE NO"));
                        cname=myRs.getString("NAME");
                        cphno=myRs.getString("PHONE NO");
		
             
			// 4. Execute SQL query
			
    }catch (SQLException exc) {
			exc.printStackTrace();
		}
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        inname = new javax.swing.JLabel();
        inphno = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        r1 = new javax.swing.JRadioButton();
        r2 = new javax.swing.JRadioButton();
        r3 = new javax.swing.JRadioButton();
        r4 = new javax.swing.JRadioButton();
        r5 = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 255, 153));

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        inname.setText("Name:");

        inphno.setText("Phone no:");

        jButton1.setText("Call Completion check");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Call request Report");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inname)
                    .addComponent(inphno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inname)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inphno)
                    .addComponent(jButton2))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Enter your pincode to check whether the service is available or not");

        jButton3.setText("CHECK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("RESET");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("SERVICES AS OF NOW AVAILABLE");

        jLabel3.setText("HOSPITAL BED:");

        jLabel4.setText("MEDICINE:");

        jLabel5.setText("PLASMA REQUERIED:");

        jLabel6.setText("FOOD SERVICES");

        jLabel7.setText("ALL OF THE ABOVE:");

        r1.setBackground(new java.awt.Color(51, 255, 153));
        r1.setEnabled(false);

        r2.setBackground(new java.awt.Color(51, 255, 153));
        r2.setEnabled(false);

        r3.setBackground(new java.awt.Color(51, 255, 153));
        r3.setEnabled(false);

        r4.setBackground(new java.awt.Color(51, 255, 153));
        r4.setEnabled(false);

        r5.setBackground(new java.awt.Color(51, 255, 153));
        r5.setEnabled(false);
        r5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r5ActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 204, 102));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel2MouseExited(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("SUBMIT THE FORM");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel8)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 24, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))))
            .addComponent(jSeparator1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(96, 96, 96)
                                .addComponent(jLabel2)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(r1)
                            .addComponent(r2)
                            .addComponent(r3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(r4, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(r5, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jButton3)
                                            .addComponent(jButton4))
                                        .addGap(18, 18, 18)
                                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel2)
                                        .addGap(38, 38, 38)
                                        .addComponent(jLabel3))
                                    .addComponent(r1))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(r2)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(r3)
                                    .addComponent(jLabel5))
                                .addGap(21, 21, 21)
                                .addComponent(jLabel6))
                            .addComponent(r4))
                        .addGap(25, 25, 25)
                        .addComponent(jLabel7))
                    .addComponent(r5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("tab1", jPanel1);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 410, 630));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
     jTextField1.setText(null);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       Connection myConn = null;
		PreparedStatement myStmt = null;
		ResultSet myRs = null;
		
		try {
			// 1. Get a connection to database
			myConn = DriverManager.getConnection("jdbc:mysql://localhost:3306/pincode", "root" , "Kuld1972poon");
			
			// 2. Prepare statement
                        String query = "SELECT DISTINCT PINCODE FROM `pincode`.`list(p1)`"+"WHERE PINCODE = ?"+"AND `ENABLE/DISABLE`=1";
			myStmt = myConn.prepareStatement(query);
			
			// 3. Set the parameters
			
			myStmt.setString(1, jTextField1.getText());
			
			// 4. Execute SQL query
			myRs = myStmt.executeQuery();
                       
                        if(myRs.next()==false){
                            JOptionPane.showMessageDialog(null,"We are sorry to inform you that there are no services in the given pincode:"+jTextField1.getText()+"Please Try Again later!");
                            jTextField1.setText(null);
                        }
                        else
                        {
                            JOptionPane.showMessageDialog(null,"SERVICES are active in the pincode:"+jTextField1.getText());
                            r1.setEnabled(true);
                            r2.setEnabled(true);
                            r3.setEnabled(true);
                            r4.setEnabled(true);
                            r5.setEnabled(true);
                        }
    }catch (SQLException exc) {
			exc.printStackTrace();
		}
    }//GEN-LAST:event_jButton3ActionPerformed

    private void r5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r5ActionPerformed
        if(r5.isSelected())   {               
                            r1.setSelected(false);
                            r2.setSelected(false);
                            r3.setSelected(false);
                            r4.setSelected(false);
                            r1.setEnabled(false);
                            r2.setEnabled(false);
                            r3.setEnabled(false);
                            r4.setEnabled(false);
        }
        else
        {
             r1.setEnabled(true);
                            r2.setEnabled(true);
                            r3.setEnabled(true);
                            r4.setEnabled(true);
        }
    }//GEN-LAST:event_r5ActionPerformed

    private void jPanel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseEntered
      jPanel2.setBackground(new Color(0,255,102) );
    }//GEN-LAST:event_jPanel2MouseEntered

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
       int i= JOptionPane.showConfirmDialog(null,"WARNING.ONCE YOU RAISE A CALL,YOU WILL NOT BE ABLE TO GENERATE AN ANOTHER CALL TILL OUR TEAM IS WORKING ON A PREVIOUS CALL OF YOURS.\nPLEASE MAKE SURE THAT YOU HAVE MARKED THE  NEED YOU WANT.\nDO YOU WANT TO RAISE THE CALL?","CONFIRM",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
       if(i==JOptionPane.YES_OPTION){
        Connection myConn = null;
		PreparedStatement myStmt = null;
                PreparedStatement myStmt1=null;
		ResultSet myRs = null;
                
		
		try {
			// 1. Get a connection to database
			myConn = DriverManager.getConnection("jdbc:mysql://localhost:3306/pincode", "root" , "Kuld1972poon");
			 String query = "SELECT * FROM `pincode`.`callreport`"+"WHERE `PHONE NO`=?";
                         myStmt = myConn.prepareStatement(query);
			myStmt.setString(1,cphno);
			myRs = myStmt.executeQuery();
                          if(myRs.next()==false){
                              String query1 = "INSERT INTO `pincode`.`callreport`(`NAME`,`PHONE NO`,`HOSPITAL`,`PHARMACY`,`PLASMA`,`FOOD`,`REV ID`,`COMPLETED`)VALUES(?,?,?,?,?,?,?,0)";
                              myStmt= myConn.prepareStatement(query1);
                                 getcurrentrev ob1 = new getcurrentrev();
                                  j = ob1.readfromfile();
                                  
                                  finallist(j);
                                  System.out.println(+j);
                                  myStmt.setString(1,cname );
                                  myStmt.setString(2,cphno);
                                  if(r5.isSelected()){
                                      myStmt.setString(3,"YES");
                                      myStmt.setString(4,"YES");
                                      myStmt.setString(5,"YES");
                                      myStmt.setString(6 ,"YES");
                                      
                                  }
                                  else
                                  {
                                      if(r1.isSelected()){
                                          myStmt.setString(3,"YES");
                                      }
                                      else{
                                          myStmt.setString(3,"NO");
                                      }
                                      if(r2.isSelected()){
                                          myStmt.setString(4,"YES");
                                      }
                                      else{
                                          myStmt.setString(4,"NO");
                                      }
                                      if(r3.isSelected()){
                                          myStmt.setString(5,"YES");
                                      }
                                      else{
                                          myStmt.setString(5,"NO");
                                      }
                                      if(r4.isSelected())
                                      {
                                           myStmt.setString(6 ,"YES");
                                      }
                                      else
                                           myStmt.setString(6 ,"NO");
                                      
                                  }
                                  myStmt.setString(7,rid);
                                  myStmt.executeUpdate();
                                  j++;
                                  ob1.writetofile(j);
                                  JOptionPane.showMessageDialog(null,"CALL BOOKED!");
                          }else{
                              JOptionPane.showMessageDialog(null,"CALL HAS BEEN ALREADY BOOKED.PLEASE WAIT WHILE WE FINISH THE PREVIOUS CALL.");
                          }
                              
    }catch (SQLException exc) {
			exc.printStackTrace();
		}
       }
    }//GEN-LAST:event_jPanel2MouseClicked

    private void jPanel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseExited
        jPanel2.setBackground(new Color(0,204,102) );
    }//GEN-LAST:event_jPanel2MouseExited

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
          Connection myConn = null;
		PreparedStatement myStmt = null;
		ResultSet myRs = null;
		
		try {
			// 1. Get a connection to database
			myConn = DriverManager.getConnection("jdbc:mysql://localhost:3306/pincode", "root" , "Kuld1972poon");
			
			// 2. Prepare statement
                        String query = "SELECT * FROM `pincode`.`callreport`"+"WHERE `NAME` = ?"+"AND `PHONE NO`=?";
			myStmt = myConn.prepareStatement(query);
                        myStmt.setString(1, cname);
                        myStmt.setString(2,cphno);
                        myRs=myStmt.executeQuery();
                        myRs.next();
                         lo=myRs.getInt("COMPLETED");
                        if(lo==0){
                            JOptionPane.showMessageDialog(null,"Your Call is still in progress.\nPlease wait as our team is trying our best to finish your call");
                        }
                        else{
                            JOptionPane.showMessageDialog(null,"Your call has been closed succesfully.\nPlease click the call request report button to know about your call");
                        }
			
			
			
			
    }catch (SQLException exc) {
			exc.printStackTrace();
		}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(lo==0){
            JOptionPane.showMessageDialog(null,"Please wait for the report to be generated");
        }
        else{
        report frame= new report();
        frame.setup(k,l);
        frame.setVisible(true);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(surveyform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(surveyform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(surveyform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(surveyform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new surveyform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel inname;
    private javax.swing.JLabel inphno;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JRadioButton r1;
    private javax.swing.JRadioButton r2;
    private javax.swing.JRadioButton r3;
    private javax.swing.JRadioButton r4;
    private javax.swing.JRadioButton r5;
    // End of variables declaration//GEN-END:variables
}
